### ISSUE TITLE
Why fork?

### ISSUE THREAD

**Issue by Jayman2000** [InsanityBringer/PiccuEngine#14]
Why did you choose to create a fork rather than contributing these features upstream?

I’m not trying to argue for or against forking. I just don’t really understand what the benefit is.

**Comment by InsanityBringer** [comment]
I have no opposition to submitting upstream, but my changes are for the most part out of scope with the current goals. I have a pile of fixes I've been sitting on for a while from the InjectD3 project, I just feel like it would be nice to get them out to people.

**Comment by Jayman2000** [comment]
> my changes are for the most part out of scope with the current goals.

What are the current goals of the upstream project?

**Comment by InsanityBringer** [comment]
ATM they're working on a relatively conservative 1.5 stable baseline that would then be used for feature development in the future

**Comment by MasterO2** [comment]
> ATM they're working on a relatively conservative 1.5 stable baseline that would then be used for feature development in the future

At the end of the day, you can just sync your fork with upstream anyway, so you'll have all of their work from upstream as well as your own.

**Comment by Jayman2000** [comment]
> At the end of the day, you can just sync your fork with upstream anyway, so you'll have all of their work from upstream as well as your own.

See, this is part of my dilemma. If I contribute upstream, then everyone (including the forks) will benefit from my contributions. The problem is: upstream is picky, and they’ve already rejected [some of](https://github.com/DescentDevelopers/Descent3/issues/62) [my](https://github.com/DescentDevelopers/Descent3/issues/264) [ideas](https://github.com/DescentDevelopers/Descent3/issues/265). If I contribute to this project, my changes have a better change of being accepted, but then the contributions won’t make it to everybody.

That’s why I asked this question in the first place. I’m kind of stuck between multiple projects and I don’t know where to contribute.
