### ISSUE TITLE
Text corrupted when scrolling off the top of the screen

### ISSUE THREAD

**Issue by Broken-Thumbs** [InsanityBringer/PiccuEngine#19]
Piccu Engine v1.0.1
Windows 10
RTX 3080
Ryzen 5800X3D
![Corrupted text](https://github.com/InsanityBringer/PiccuEngine/assets/1777045/fac21ce3-0932-42f9-8b6d-ad667baca18f)

**Comment by InsanityBringer** [comment]
how did I forget about this one? I remember studying grtext long ago and realizing the text clipper doesn't handle scaling right. I'll have to find a solution for that.
