### ISSUE TITLE
Brightness setting in game has no function.

### ISSUE THREAD

**Issue by SunSpireUK** [InsanityBringer/PiccuEngine#20]
Hello! 

First I'd like to say Thank You to the developer for this wonderful new engine that brings D3 into the modern age! Unstretched widescreen support. It's simply AWESOME! 

Tonight I gave it a quick playtest, it works fine in Windows 7 (yes, I still use it occasionally) as well as Windows 10. However, the brightness slider in the options menu does not function. While I can set it to a higher or lower value, it does not affect the image output at all. 

While the game is perfectly playable in Win7, as the pre-set brightness is just right, in Win10 it is extremely dark (at least for me), so dark in fact I can't make out the text on the main menu buttons and in-game levels are way too dark to see anything. 

No matter what settings I tinkered with in the NVidia CP, I could not get the game any brighter. Not sure why that is? 

(i5 4670 3,4 GHZ / 16GB RAM / RTX 3080 TI)

**Comment by InsanityBringer** [comment]
Descent 3 did gamma adjustments by changing the global device gamma ramp, which I don't consider acceptable for a game to do today. I'll have to implement brightness through a shader function, and I have some ideas on how to do it.
