### ISSUE TITLE
Portable Install Keeps Asking Me If I Want To Be Portable

### ISSUE THREAD

**Issue by TheKins** [InsanityBringer/PiccuEngine#23]
I have Descent 3 and Piccu both installed in D:\Games\GOG.com\Descent 3 with a "piccu_portable" file present in the same directory. Upon booting Piccu up, it will always ask me if I want to make my install portable.

**Comment by InsanityBringer** [comment]
This is known and will be fixed in the upcoming 1.1 version. I want to release that today if I don't have any other surprises.
