### ISSUE TITLE
Weird Vsync

### ISSUE THREAD

**Issue by Glowhyena** [InsanityBringer/PiccuEngine#26]
Something is wrong with the vsync in the game. If enabled, FPS is uncapped and the animated textures, such as force fields animate too fast. If disabled, on the other hand, FPS is capped. Could you check the video?

https://youtu.be/Q7qfrq82Ses

**Comment by InsanityBringer** [comment]
By any chance do you have a nvidia card, and if you do, do you use gsync? I made a seemingly bad decision to leave the only timing between frames be the SwapBuffers call blocking, but this doesn't seem to work as intended from people with nvidia cards and the game runs too fast as a result.

**Comment by Sol1vaN** [comment]
i'm using rtx 2070:
on my case i've turned on the vsync option in the game + gsync enabled only for full screen/exclusive display.
also i've capped the fps to 144 vía MSI Afterburner (RivaTunner Statictics) and forced the vsync to 'fast' vía nvidia control panel.
for my, is not too noticeable the fast animated textures, but i confirm the problem is present.

however, the smoothness of the entire game is ppperfect
until now the game runs flawessly.

**Comment by Glowhyena** [comment]
> By any chance do you have a nvidia card, and if you do, do you use gsync? I made a seemingly bad decision to leave the only timing between frames be the SwapBuffers call blocking, but this doesn't seem to work as intended from people with nvidia cards and the game runs too fast as a result.

Yes, I have a Nvidia card, my YouTube video says it's RTX 3070.

Fortunately, I enabled vsync on the Nvidia Control Panel and disabled the in-game vsync. The game now ran smoothly, with no choppiness or stuttering anymore! I think allowing the video to card's vsync is the solution.

**Comment by Sol1vaN** [comment]
i know that threat is closed, but

i've found a great idea to solve the animated texture speed:
![image](https://github.com/user-attachments/assets/1c73fabd-7afa-4842-a7d6-e896bff16bb2)

if you see, old unreal in his last testing patch 2.27k, they added a new option in unreal.ini file called "AnimTexFrameRate" making the animated textures works at the exact speed the engine was designed to handle.

```
[Engine.GameInfo]
AnimTexFrameRate=42.000000
```

seems that the animated textures on old unreal originally works at 42fps to look in the way that developers wants.

source:
https://github.com/OldUnreal/Unreal-testing
