### ISSUE TITLE
[Suggestion] Better handling of FMV in widescreen.

### ISSUE THREAD

**Issue by TheKins** [InsanityBringer/PiccuEngine#31]
The FMVs in the original Retribution campaign are in 16:9 aspect ratio in an era where most players had 4:3 displays. As such, Descent 3 letterboxes them. Currently, Piccu adds pillarboxes to _that_, resulting in FMVs being confined to a small rectangle when they could be blown up to take up more (or all) of the screen.

![alt text](https://i.imgur.com/fuW6j0x.png)

Granted, there's probably a LOT of stuff to do for video playback, but I figured I'd put this down on paper for future reference. :)

**Comment by InsanityBringer** [comment]
Honestly I don't think this will be too hard, I can look into it for the next release.

**Comment by smeep0** [comment]
Also please take ultrawide resolutions into considering as well! (i.e. 21:9/32:9 aspect ratio monitors)
