### ISSUE TITLE
[QUESTION] What means 'PPS' referenced in v1.1.1 release?

### ISSUE THREAD

**Issue by Sol1vaN** [InsanityBringer/PiccuEngine#35]
This:

Default PPS bumped to 30.
PPS range in dedicated config can go up to 40 now.

Sorry for the question, but I can't find nothing explained of it here.
🤷‍♂️

**Comment by InsanityBringer** [comment]
packets per second. it's how often your game sends updates of your ship position to the other players. it was low because connections used to be slower and less reliable, but now it can go higher, and players prefer smoother gameplay.
