### ISSUE TITLE
Broken terrain UV coordinates after v1.1.1

### ISSUE THREAD

**Issue by rimisuko** [InsanityBringer/PiccuEngine#48]
Hi there,

Just a heads-up in case the issue below isn't already known:

With the current master branch (date 24/06/15, compiled with VSCode/VC++ 2022 on Windows 11, everything at default) there is some UV coordinate corruption related to terrain rendering that must have snuck in after v1.1.1. The screenshot below should make the issue pretty obvious:

![piccu_terrain_uv-glitch](https://github.com/InsanityBringer/PiccuEngine/assets/97134303/abb1c0b0-4a21-479c-8f38-ac476087e2f2)

**Comment by InsanityBringer** [comment]
Which level is this from? I'm still working on a few bugs with the new rendering code and I'd like to be able to double check it

**Comment by rimisuko** [comment]
That's the Titan level (11, PTMC Storage Facility). I attached a savegame for convenience. Should have done that in the original post.

[savegame.zip](https://github.com/user-attachments/files/15865341/savegame.zip)

**Comment by rimisuko** [comment]
On a sidenote: When you fly around a bit, you'll also notice weird "sliding" terrain geometry where structures/buildings hit the ground. Very obvious when you fly towards a building from far away. Might be a z-buffer problem from the looks of it, but that's just a guess.

This issue also isn't present in v1.1.1
