### ISSUE TITLE
X-Box controller pitch/heading configuration overridden by Z-axis

### ISSUE THREAD

**Issue by megamangk** [InsanityBringer/PiccuEngine#58]
When attempting to configure pitch/heading controls with an X-Box controller on a Windows machine, the axis configuration is overridden by Z-axis. This may be because Windows sees the Z axis on an X-Box controller as a slider instead of an actual axis, thus assumes input is being actioned. However, this was not an issue prior to Piccu v1.2.2.

**Comment by vitosky66** [comment]
Check is these fixes resolve your problems:

https://github.com/beterhans/x2dcli

https://www.reddit.com/r/xbox/comments/qer8pv/xbox_controller_right_and_left_trigger_merged/
