### ISSUE TITLE
Forward/Reverse Movement With Keyboard is Extremely Slow

### ISSUE THREAD

**Issue by BigheadSMZ** [InsanityBringer/PiccuEngine#61]
This is a really strange issue. For some reason when trying to move forward with the default A key (or any key via remapping), the ship moves forward very very slowly. Like you could mistake it for standing still if not looking closely. The same issue happens with reverse. But if I bind a gamepad button to forward or reverse, it moves at normal speed. 

I would really like to play using my PS5 controller which I have emulated as XB360 controller with DS4Windows, but I can't seem to find a come up with a good control scheme. For example, for some reason it does not let me assign an axis direction to slide, which I could probably come up with some clever workarounds but for now I'm just trying to play with keyboard and mouse. And currently, that's not possible due to the almost no movement bug.

**Comment by InsanityBringer** [comment]
I pushed a fix that should prevent this in the future, but to make it work now, please go to Options->Config->Keyboard->Adjust Settings and nudge the key ramping slider up and then down again. This *should* fix the bug
