### ISSUE TITLE
Antialiasing bug.

### ISSUE THREAD

**Issue by mole973102** [InsanityBringer/PiccuEngine#66]
![Crash!](https://github.com/user-attachments/assets/f903e16c-32eb-4b29-918e-92db32ec6e61)
is caused by...
Antialiasing from OFF to ON.

The issue writes something somewhere and I have no idea where.  Is set to Portable Mode, but cannot see anything in the Portable Folder.  If I restore my Windows backup, folder works, so wonder if a Registry or file in System32 etc.  If I had not got a way to restore my Windows build, I would be locked out, as no idea what is being written and to where.

---
I also find (as per notes) that when I first run, with a new Player file, I have to tease the keyboard config.

**Comment by mole973102** [comment]
[2024-11-05T02-53-10Z-dump.zip](https://github.com/user-attachments/files/17626520/2024-11-05T02-53-10Z-dump.zip)
File in error box.

**Comment by InsanityBringer** [comment]
Crash seems to be when calling glCheckFramebufferStatus. I have no idea what would cause this, but for the moment I'm disabling the check in non-debug builds. (There should be no reason for it to run in release builds anyways)

**Comment by mole973102** [comment]
A thought has just occurred to me.  I am running Windows 11 Pro on a machine that isn't supposed to.  And the graphics card is not really supported under 11.  So, it actually may not be you, it might be my hacky driver.  I get a quirk with a couple of monitors with this card too, but my usual monitors are okay.  I'd like a better driver, but there isn't one.

The bigger issue here, is how to undo this bug if triggered.  I was able to roll back, or otherwise I would have had problems as no idea what has been added and so where to remove it!  As it won't run, I could not turn the checkbox off.  It did not appear to save in the main game folder.

**Comment by InsanityBringer** [comment]
Currently configuration is stored in the registry on Windows, like vanilla (I should change it to a text configuration file). Open up regedit and make your way over to `Computer\HKEY_CURRENT_USER\SOFTWARE\Outrage\Descent3` and change the `rs_antialiased` key to turn it off.

**Comment by mole973102** [comment]
It would be nice yes, if the game could be fully portable as opposed to the Registry.
Thank you.  :)
