### ISSUE TITLE
Couple of install questions...

### ISSUE THREAD

**Issue by mole973102** [InsanityBringer/PiccuEngine#67]
Hi, couple of installation questions, if someone would be so kind...

01.  The install notes do not mention 'PPICS.HOG'.  Is this not needed?  What does it do?
02.  I have both the Descent 3 and Mercenary CDs.
      - missions/Fury.hog (stock Anarchy levels) is this a download or hidden somewhere?  Cannot see this file on the isos?
03. • ISSUE: A fresh pilot file will very likely have problems moving with the keyboard controls.
  After installation, go to: 'Options->Config->Keyboard->Adjust settings' and nudge the key ramping slider up and down once.
  (Not in the Readme, only on download, so could get overlooked).

Thanks in advance.

**Comment by mole973102** [comment]
I am guessing the PPICS.HOG is needed as graphics or something like that.
I think fury.hog should be fury.mn3 in the text file.
[readme.md](https://github.com/user-attachments/files/17653540/readme.md)

**Comment by InsanityBringer** [comment]
ppics.hog is used for the "pilot pics" feature, where people could submit a picture to be associated with their pilot name before the game was released. it's not critical, but it can be installed as desired. 

fury.hog is indeed a type, it should be fury.mn3, I will fix that.
