### ISSUE TITLE
EAX Emulation?

### ISSUE THREAD

**Issue by OpenRift412** [InsanityBringer/PiccuEngine#9]
Is EAX emulation via OpenAL already implemented? It kind of sounds like it is, but I'm not familiar enough with D3's soundscapes to tell.

Either way, maybe have like a toggle for those effects in the sound menu?

**Comment by InsanityBringer** [comment]
EAX emulation is already present (somewhat, I switched the presets to their EAX2 equivalents), but I can add a reverb option in the sound options.

Probably also a doppler strength adjust.
